version: "3"
services:
  web:
    tty: true
    stdin_open: true
    image: "ruby:2.7.0"
    ports:
      - "5000:5000"
    environment:
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    volumes:
      - ".:/web"
      - "./.bundle:/usr/local/bundle"
    working_dir: "/web"
    command: "bundle exec ruby app.rb -o 0.0.0.0 -p 5000"
  redis:
    image: redis
    ports:
      - "6379:6379"